banking_dbt:
  outputs:
    dev:
      account: rk63526.ca-central-1.aws
      database: banking
      password: Rhamdasari@1998
      role: accountadmin
      schema: analytics
      threads: 4
      type: snowflake
      user: Manisha
      warehouse: COMPUTE_WH
  target: dev
